const tokenStore = new Map();
const pendingStates = new Set();
// Tracks which user initiated each OAuth state, so a token obtained under
// one user's flow can't be claimed by a different authenticated user who
// happens to learn or guess the state value (states are short, random
// strings — not secret once passed through the popup/postMessage flow).
const stateOwners = new Map();

function getClient() {
  // Required lazily (not at module load) — `googleapis` is large and
  // measurably slow to load, and most requires of this module (e.g. the
  // pending-state bookkeeping functions below) don't need it at all.
  const { google } = require('googleapis');
  return new google.auth.OAuth2(
    process.env.GOOGLE_CLIENT_ID,
    process.env.GOOGLE_CLIENT_SECRET,
    process.env.GOOGLE_REDIRECT_URI || 'http://localhost:3000/auth/google/callback'
  );
}
function registerPendingState(state, userId) {
  pendingStates.add(state);
  stateOwners.set(state, userId);
  // Auto-expire after 10 minutes so these maps don't grow forever. Only
  // clear ownership if the tokens were never claimed — removeTokens()
  // already clears it for the normal (claimed) path.
  const cleanup = setTimeout(() => {
    pendingStates.delete(state);
    if (!tokenStore.has(state)) stateOwners.delete(state);
  }, 10 * 60 * 1000);
  // Don't let this cleanup timer keep the Node process alive (matters for
  // graceful shutdown and for test runners that expect the process to exit
  // once work is done).
  cleanup.unref?.();
}

// Returns true and removes the state if it was generated by this server
function verifyPendingState(state) {
  if (!pendingStates.has(state)) return false;
  pendingStates.delete(state);
  return true;
}

function storeTokens(state, tokens) {
  tokenStore.set(state, tokens);
}
// Only returns tokens if `state` was originally registered by `userId` —
// prevents one authenticated user from riding another user's in-flight
// Google OAuth state to access their tokens.
function getTokens(state, userId) {
  if (stateOwners.get(state) !== userId) return undefined;
  return tokenStore.get(state);
}
// Lets the opener tab poll for completion instead of relying on
// window.opener.postMessage from the popup — Google's own accounts.google.com
// pages send `Cross-Origin-Opener-Policy: same-origin`, which permanently
// severs window.opener the moment the popup navigates there, breaking the
// postMessage-based handoff regardless of anything this app does.
function hasTokens(state, userId) {
  return stateOwners.get(state) === userId && tokenStore.has(state);
}
function removeTokens(state) {
  tokenStore.delete(state);
  stateOwners.delete(state);
}

module.exports = {
  getClient,
  registerPendingState,
  verifyPendingState,
  storeTokens,
  getTokens,
  hasTokens,
  removeTokens,
};
