const router = require('express').Router();
const { getClient, storeTokens, verifyPendingState } = require('../services/googleAuth');

const CLIENT_ORIGIN = process.env.CLIENT_ORIGIN || 'http://localhost:5173';

// GET /auth/google/callback
router.get('/callback', async (req, res) => {
  const { code, state } = req.query;
  if (!code || !state) return res.status(400).send('Missing code or state');

  // Reject states not generated by this server (CSRF protection)
  if (!verifyPendingState(state)) return res.status(400).send('Invalid or expired state');

  try {
    const client = getClient();
    const { tokens } = await client.getToken(code);
    storeTokens(state, tokens);

    // Use JSON.stringify to safely embed state into JS (prevents XSS)
    const safeState = JSON.stringify(state);
    const safeOrigin = JSON.stringify(CLIENT_ORIGIN);
    res.send(`<!DOCTYPE html><html><body><script>
      if (window.opener) {
        window.opener.postMessage({ type: 'google-oauth-done', state: ${safeState} }, ${safeOrigin});
      }
      window.close();
    </script></body></html>`);
  } catch (e) {
    console.error('Google OAuth error:', e.message);
    res.status(500).send('Google authorization failed. Please close this window and try again.');
  }
});

module.exports = router;
